/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rafael.biblioteca;

import java.io.IOException;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
		dtd = "-//com.rafael.biblioteca//MainWindow//EN",
		autostore = false
)
@TopComponent.Description(
		preferredID = "MainWindowTopComponent",
		//iconBase="SET/PATH/TO/ICON/HERE", 
		persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "com.rafael.biblioteca.MainWindowTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
		displayName = "#CTL_MainWindowAction",
		preferredID = "MainWindowTopComponent"
)
@Messages({
	"CTL_MainWindowAction=Biblioteca",
	"CTL_MainWindowTopComponent=Biblioteca",
	"HINT_MainWindowTopComponent=Esta es la biblioteca"
})
public final class BibliotecaWindow extends TopComponent {

	public BibliotecaWindow() {
		initComponents();
		setName(Bundle.CTL_MainWindowTopComponent());
		setToolTipText(Bundle.HINT_MainWindowTopComponent());
		putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
		putClientProperty(TopComponent.PROP_DRAGGING_DISABLED, Boolean.TRUE);
		putClientProperty(TopComponent.PROP_UNDOCKING_DISABLED, Boolean.TRUE);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabs = new javax.swing.JTabbedPane();
        librosTab = new javax.swing.JPanel();
        librosTableScroll = new javax.swing.JScrollPane();
        librosTable = new javax.swing.JTable();
        librosTitle = new javax.swing.JLabel();
        librosAgragarButton = new javax.swing.JButton();
        librosEditarButton = new javax.swing.JButton();
        librosExtraerButton = new javax.swing.JButton();
        librosEliminarButton = new javax.swing.JButton();

        mainTabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        librosTable.setModel(new TablaLibrosModel());
        librosTableScroll.setViewportView(librosTable);

        librosTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librosTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.openide.awt.Mnemonics.setLocalizedText(librosTitle, org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosTitle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(librosAgragarButton, org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosAgragarButton.text")); // NOI18N
        librosAgragarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosAgragarButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(librosEditarButton, org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosEditarButton.text")); // NOI18N
        librosEditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosEditarButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(librosExtraerButton, org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosExtraerButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(librosEliminarButton, org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosEliminarButton.text")); // NOI18N
        librosEliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librosEliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout librosTabLayout = new javax.swing.GroupLayout(librosTab);
        librosTab.setLayout(librosTabLayout);
        librosTabLayout.setHorizontalGroup(
            librosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(librosTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(librosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(librosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librosTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(librosTabLayout.createSequentialGroup()
                        .addComponent(librosAgragarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librosEditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(librosExtraerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(librosEliminarButton)))
                .addContainerGap())
        );
        librosTabLayout.setVerticalGroup(
            librosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(librosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librosTitle)
                .addGap(20, 20, 20)
                .addComponent(librosTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(librosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(librosAgragarButton)
                    .addComponent(librosEditarButton)
                    .addComponent(librosExtraerButton)
                    .addComponent(librosEliminarButton))
                .addContainerGap())
        );

        mainTabs.addTab(org.openide.util.NbBundle.getMessage(BibliotecaWindow.class, "BibliotecaWindow.librosTab.TabConstraints.tabTitle"), librosTab); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabs)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void librosAgragarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosAgragarButtonActionPerformed
		mainTabs.add(new AgregarTab(), "Agregar", 1);
		mainTabs.setSelectedIndex(1);
		mainTabs.setEnabledAt(0, false);
    }//GEN-LAST:event_librosAgragarButtonActionPerformed

    private void librosEliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosEliminarButtonActionPerformed
		int id = Integer.parseInt(librosTable.getValueAt(librosTable.getSelectedRow(), 0).toString());
		try {
			BibliotecaDB db = BibliotecaDB.getInstance();
			db.delete(id);
		} catch (IOException ex) {
			Exceptions.printStackTrace(ex);
		} catch (ClassNotFoundException ex) {
			Exceptions.printStackTrace(ex);
		}
		
    }//GEN-LAST:event_librosEliminarButtonActionPerformed

    private void librosEditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librosEditarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librosEditarButtonActionPerformed

	public static void removTab(int index) {
		mainTabs.remove(index);
	}
	
	public static void setTabEnabled(int index, boolean enabled) {
		mainTabs.setEnabledAt(index, enabled);
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton librosAgragarButton;
    private javax.swing.JButton librosEditarButton;
    private javax.swing.JButton librosEliminarButton;
    private javax.swing.JButton librosExtraerButton;
    private javax.swing.JPanel librosTab;
    private javax.swing.JTable librosTable;
    private javax.swing.JScrollPane librosTableScroll;
    private javax.swing.JLabel librosTitle;
    private static javax.swing.JTabbedPane mainTabs;
    // End of variables declaration//GEN-END:variables
	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
		try {
			BibliotecaDB.getInstance().commit();
		} catch (IOException e) {
			System.out.println("IOException: " + e.getMessage());
		} catch (ClassNotFoundException e) {
			System.out.println("ClassNotFoundException: " + e.getMessage());
		}
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}
}
